// <auto-generated />
using System;
using AirplaneProject.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AirplaneProject.Infrastructure.Migrations
{
	[DbContext(typeof(GestaoEsdContext))]
	[Migration("20191015111025_AS002")]
	partial class AS002
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
				.HasAnnotation("Relational:MaxIdentifierLength", 128)
				.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

			modelBuilder.Entity("Automacao.Core.Models.Agente", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<string>("Codigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<string>("Descricao")
					.HasMaxLength(255);

				b.Property<string>("Nome")
					.IsRequired()
					.HasMaxLength(50);

				b.HasKey("Id");

				b.ToTable("Agentes");
			});

			modelBuilder.Entity("Automacao.Core.Models.AnpNivel", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<string>("Codigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<string>("Descricao")
					.IsRequired()
					.HasMaxLength(255);

				b.Property<string>("Nome")
					.IsRequired()
					.HasMaxLength(50);

				b.HasKey("Id");

				b.ToTable("AnpNiveis");
			});

			modelBuilder.Entity("Automacao.Core.Models.Ativo", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<string>("Codigo")
					.IsRequired()
					.HasMaxLength(20);

				b.Property<string>("Nome")
					.IsRequired()
					.HasMaxLength(20);

				b.Property<int>("UnidadeOperativaId");

				b.HasKey("Id");

				b.HasIndex("Codigo")
					.IsUnique()
					.HasName("IX_Ativos_Codigo");

				b.HasIndex("UnidadeOperativaId");

				b.ToTable("Ativos");
			});

			modelBuilder.Entity("Automacao.Core.Models.Causa", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<string>("Codigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<string>("Descricao")
					.HasMaxLength(255);

				b.Property<string>("Nome")
					.IsRequired()
					.HasMaxLength(50);

				b.HasKey("Id");

				b.HasIndex("Codigo")
					.HasName("IX_Causas_Codigo");

				b.ToTable("Causas");
			});

			modelBuilder.Entity("Automacao.Core.Models.Esd", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<string>("ChaveUsuario")
					.IsRequired()
					.HasMaxLength(12);

				b.Property<DateTime>("DataEvento");

				b.Property<DateTime>("DataRegistro");

				b.Property<string>("Descricao")
					.HasMaxLength(255);

				b.Property<string>("DescricaoCodigo")
					.HasMaxLength(512);

				b.Property<int>("EventoIniciadorId");

				b.Property<int>("MotivoCausaId");

				b.Property<int>("NivelOperacaoId");

				b.Property<int>("OrigemAgenteId");

				b.Property<int>("UepId");

				b.HasKey("Id");

				b.HasIndex("DescricaoCodigo")
					.HasName("IX_Esds_Codigo");

				b.HasIndex("EventoIniciadorId");

				b.HasIndex("MotivoCausaId");

				b.HasIndex("NivelOperacaoId");

				b.HasIndex("OrigemAgenteId");

				b.HasIndex("UepId");

				b.ToTable("Esds");
			});

			modelBuilder.Entity("Automacao.Core.Models.Evento", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<string>("Codigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<string>("Descricao")
					.HasMaxLength(255);

				b.Property<string>("Nome")
					.IsRequired()
					.HasMaxLength(50);

				b.HasKey("Id");

				b.HasIndex("Codigo")
					.HasName("IX_Eventos_Codigo");

				b.ToTable("Eventos");
			});

			modelBuilder.Entity("Automacao.Core.Models.EventoIniciador", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<int>("EventoId");

				b.Property<int>("IniciadorId");

				b.HasKey("Id");

				b.HasIndex("EventoId");

				b.HasIndex("IniciadorId");

				b.ToTable("EventoIniciadores");
			});

			modelBuilder.Entity("Automacao.Core.Models.Historico", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<string>("ChaveUsuario")
					.IsRequired()
					.HasMaxLength(12);

				b.Property<DateTime>("DataAlteracao");

				b.Property<DateTime>("DataEvento");

				b.Property<DateTime>("DataRegistro");

				b.Property<string>("Descricao")
					.HasMaxLength(255);

				b.Property<string>("DescricaoCodigo")
					.HasMaxLength(512);

				b.Property<int>("EsdId");

				b.Property<int>("EventoIniciadorId");

				b.Property<int>("MotivoCausaId");

				b.Property<int>("NivelOperacaoId");

				b.Property<int>("OrigemAgenteId");

				b.Property<int>("UepId");

				b.HasKey("Id");

				b.HasIndex("DescricaoCodigo")
					.HasName("IX_Historicos_Codigo");

				b.HasIndex("EsdId");

				b.HasIndex("EventoIniciadorId");

				b.HasIndex("MotivoCausaId");

				b.HasIndex("NivelOperacaoId");

				b.HasIndex("OrigemAgenteId");

				b.HasIndex("UepId");

				b.ToTable("Historicos");
			});

			modelBuilder.Entity("Automacao.Core.Models.Iniciador", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<string>("Codigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<string>("Descricao")
					.HasMaxLength(255);

				b.Property<string>("Nome")
					.IsRequired()
					.HasMaxLength(50);

				b.HasKey("Id");

				b.HasIndex("Codigo")
					.HasName("IX_Iniciadores_Codigo");

				b.ToTable("Iniciadores");
			});

			modelBuilder.Entity("Automacao.Core.Models.Motivo", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<string>("Codigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<string>("Descricao")
					.HasMaxLength(255);

				b.Property<string>("Nome")
					.IsRequired()
					.HasMaxLength(50);

				b.HasKey("Id");

				b.HasIndex("Codigo")
					.HasName("IX_Motivos_Codigo");

				b.ToTable("Motivos");
			});

			modelBuilder.Entity("Automacao.Core.Models.MotivoCausa", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<int>("CausaId");

				b.Property<int>("MotivoId");

				b.HasKey("Id");

				b.HasIndex("CausaId");

				b.HasIndex("MotivoId");

				b.ToTable("MotivoCausas");
			});

			modelBuilder.Entity("Automacao.Core.Models.Nivel", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<int>("AnpNivelId");

				b.Property<string>("Codigo")
					.IsRequired()
					.HasMaxLength(20);

				b.Property<string>("Descricao")
					.HasMaxLength(255);

				b.Property<string>("Nome")
					.IsRequired()
					.HasMaxLength(20);

				b.HasKey("Id");

				b.HasIndex("AnpNivelId");

				b.HasIndex("Codigo")
					.HasName("IX_Niveis_Codigo");

				b.ToTable("Niveis");
			});

			modelBuilder.Entity("Automacao.Core.Models.NivelOperacao", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<int>("NivelId");

				b.Property<int>("OperacaoId");

				b.HasKey("Id");

				b.HasIndex("NivelId");

				b.HasIndex("OperacaoId");

				b.ToTable("NivelOperacoes");
			});

			modelBuilder.Entity("Automacao.Core.Models.Operacao", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<string>("Codigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<string>("Descricao")
					.HasMaxLength(255);

				b.Property<string>("Nome")
					.IsRequired()
					.HasMaxLength(50);

				b.HasKey("Id");

				b.ToTable("Operacoes");
			});

			modelBuilder.Entity("Automacao.Core.Models.Origem", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<string>("Codigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<string>("Descricao")
					.HasMaxLength(255);

				b.Property<string>("Nome")
					.IsRequired()
					.HasMaxLength(50);

				b.HasKey("Id");

				b.HasIndex("Codigo")
					.HasName("IX_Origens_Codigo");

				b.ToTable("Origens");
			});

			modelBuilder.Entity("Automacao.Core.Models.OrigemAgente", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<int>("AgenteId");

				b.Property<int>("OrigemId");

				b.HasKey("Id");

				b.HasIndex("AgenteId");

				b.HasIndex("OrigemId");

				b.ToTable("OrigemAgentes");
			});

			modelBuilder.Entity("Automacao.Core.Models.Uep", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<int>("AtivoId");

				b.Property<string>("Codigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<string>("Descricao")
					.IsRequired()
					.HasMaxLength(255);

				b.Property<string>("Nome")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<int>("OperacaoId");

				b.Property<int>("UepTipoId");

				b.HasKey("Id");

				b.HasIndex("AtivoId");

				b.HasIndex("Codigo")
					.IsUnique()
					.HasName("IX_Ueps_Codigo");

				b.HasIndex("OperacaoId");

				b.HasIndex("UepTipoId");

				b.ToTable("Ueps");
			});

			modelBuilder.Entity("Automacao.Core.Models.UepTipo", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<string>("Codigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<string>("Descricao")
					.HasMaxLength(255);

				b.Property<string>("Nome")
					.IsRequired()
					.HasMaxLength(50);

				b.HasKey("Id");

				b.HasIndex("Codigo")
					.HasName("IX_UepTipos_Codigo");

				b.ToTable("UepTipos");
			});

			modelBuilder.Entity("Automacao.Core.Models.UnidadeOperativa", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<string>("Codigo")
					.IsRequired()
					.HasMaxLength(20);

				b.Property<string>("Nome")
					.IsRequired()
					.HasMaxLength(20);

				b.HasKey("Id");

				b.HasIndex("Codigo")
					.IsUnique()
					.HasName("IX_UnidadesOperativas_Codigo");

				b.ToTable("UnidadesOperativas");
			});

			modelBuilder.Entity("Automacao.Core.Models.Views.EsdView", b =>
			{
				b.Property<int>("Id")
					.ValueGeneratedOnAdd()
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

				b.Property<string>("AgenteCodigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<int>("AgenteId");

				b.Property<string>("AgenteNome")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<string>("AtivoCodigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<int>("AtivoId");

				b.Property<string>("AtivoNome")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<string>("CausaCodigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<int>("CausaId");

				b.Property<string>("CausaNome")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<DateTime>("DataEvento");

				b.Property<string>("Descricao")
					.HasMaxLength(255);

				b.Property<string>("DescricaoCodigo")
					.HasMaxLength(255);

				b.Property<string>("EventoCodigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<int>("EventoId");

				b.Property<string>("EventoNome")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<string>("IniciadorCodigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<int>("IniciadorId");

				b.Property<string>("IniciadorNome")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<string>("MotivoCodigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<int>("MotivoId");

				b.Property<string>("MotivoNome")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<string>("NivelCodigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<int>("NivelId");

				b.Property<string>("NivelNome")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<string>("OrigemCodigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<int>("OrigemId");

				b.Property<string>("OrigemNome")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<string>("UepCodigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<int>("UepId");

				b.Property<string>("UepNome")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<string>("UnidadeCodigo")
					.IsRequired()
					.HasMaxLength(50);

				b.Property<int>("UnidadeId");

				b.Property<string>("UnidadeNome")
					.IsRequired()
					.HasMaxLength(50);

				b.HasKey("Id");

				b.ToTable("vwEsd");
			});

			modelBuilder.Entity("Automacao.Core.Models.Ativo", b =>
			{
				b.HasOne("Automacao.Core.Models.UnidadeOperativa", "UnidadeOperativa")
					.WithMany("Ativos")
					.HasForeignKey("UnidadeOperativaId")
					.OnDelete(DeleteBehavior.Restrict);
			});

			modelBuilder.Entity("Automacao.Core.Models.Esd", b =>
			{
				b.HasOne("Automacao.Core.Models.EventoIniciador", "EventoIniciador")
					.WithMany("Esds")
					.HasForeignKey("EventoIniciadorId")
					.OnDelete(DeleteBehavior.Restrict);

				b.HasOne("Automacao.Core.Models.MotivoCausa", "MotivoCausa")
					.WithMany("Esds")
					.HasForeignKey("MotivoCausaId")
					.OnDelete(DeleteBehavior.Restrict);

				b.HasOne("Automacao.Core.Models.NivelOperacao", "NivelOperacao")
					.WithMany("Esds")
					.HasForeignKey("NivelOperacaoId")
					.OnDelete(DeleteBehavior.Restrict);

				b.HasOne("Automacao.Core.Models.OrigemAgente", "OrigemAgente")
					.WithMany("Esds")
					.HasForeignKey("OrigemAgenteId")
					.OnDelete(DeleteBehavior.Restrict);

				b.HasOne("Automacao.Core.Models.Uep", "Uep")
					.WithMany()
					.HasForeignKey("UepId")
					.OnDelete(DeleteBehavior.Restrict);
			});

			modelBuilder.Entity("Automacao.Core.Models.EventoIniciador", b =>
			{
				b.HasOne("Automacao.Core.Models.Evento", "Evento")
					.WithMany()
					.HasForeignKey("EventoId")
					.OnDelete(DeleteBehavior.Restrict);

				b.HasOne("Automacao.Core.Models.Iniciador", "Iniciador")
					.WithMany()
					.HasForeignKey("IniciadorId")
					.OnDelete(DeleteBehavior.Restrict);
			});

			modelBuilder.Entity("Automacao.Core.Models.Historico", b =>
			{
				b.HasOne("Automacao.Core.Models.Esd", "Esd")
					.WithMany("Historicos")
					.HasForeignKey("EsdId")
					.OnDelete(DeleteBehavior.Restrict);

				b.HasOne("Automacao.Core.Models.EventoIniciador", "EventoIniciador")
					.WithMany("Historicos")
					.HasForeignKey("EventoIniciadorId")
					.OnDelete(DeleteBehavior.Restrict);

				b.HasOne("Automacao.Core.Models.MotivoCausa", "MotivoCausa")
					.WithMany("Historicos")
					.HasForeignKey("MotivoCausaId")
					.OnDelete(DeleteBehavior.Restrict);

				b.HasOne("Automacao.Core.Models.NivelOperacao", "NivelOperacao")
					.WithMany("Historicos")
					.HasForeignKey("NivelOperacaoId")
					.OnDelete(DeleteBehavior.Restrict);

				b.HasOne("Automacao.Core.Models.OrigemAgente", "OrigemAgente")
					.WithMany("Historicos")
					.HasForeignKey("OrigemAgenteId")
					.OnDelete(DeleteBehavior.Restrict);

				b.HasOne("Automacao.Core.Models.Uep", "Uep")
					.WithMany()
					.HasForeignKey("UepId")
					.OnDelete(DeleteBehavior.Restrict);
			});

			modelBuilder.Entity("Automacao.Core.Models.MotivoCausa", b =>
			{
				b.HasOne("Automacao.Core.Models.Causa", "Causa")
					.WithMany("MotivoCausas")
					.HasForeignKey("CausaId")
					.OnDelete(DeleteBehavior.Restrict);

				b.HasOne("Automacao.Core.Models.Motivo", "Motivo")
					.WithMany("MotivoCausas")
					.HasForeignKey("MotivoId")
					.OnDelete(DeleteBehavior.Restrict);
			});

			modelBuilder.Entity("Automacao.Core.Models.Nivel", b =>
			{
				b.HasOne("Automacao.Core.Models.AnpNivel", "AnpNivel")
					.WithMany("Niveis")
					.HasForeignKey("AnpNivelId")
					.OnDelete(DeleteBehavior.Restrict);
			});

			modelBuilder.Entity("Automacao.Core.Models.NivelOperacao", b =>
			{
				b.HasOne("Automacao.Core.Models.Nivel", "Nivel")
					.WithMany("NivelOperacoes")
					.HasForeignKey("NivelId")
					.OnDelete(DeleteBehavior.Restrict);

				b.HasOne("Automacao.Core.Models.Operacao", "Operacao")
					.WithMany("NivelOperacoes")
					.HasForeignKey("OperacaoId")
					.OnDelete(DeleteBehavior.Restrict);
			});

			modelBuilder.Entity("Automacao.Core.Models.OrigemAgente", b =>
			{
				b.HasOne("Automacao.Core.Models.Agente", "Agente")
					.WithMany()
					.HasForeignKey("AgenteId")
					.OnDelete(DeleteBehavior.Cascade);

				b.HasOne("Automacao.Core.Models.Origem", "Origem")
					.WithMany()
					.HasForeignKey("OrigemId")
					.OnDelete(DeleteBehavior.Cascade);
			});

			modelBuilder.Entity("Automacao.Core.Models.Uep", b =>
			{
				b.HasOne("Automacao.Core.Models.Ativo", "Ativo")
					.WithMany("Ueps")
					.HasForeignKey("AtivoId")
					.OnDelete(DeleteBehavior.Restrict);

				b.HasOne("Automacao.Core.Models.Operacao", "Operacao")
					.WithMany("Ueps")
					.HasForeignKey("OperacaoId")
					.OnDelete(DeleteBehavior.Cascade);

				b.HasOne("Automacao.Core.Models.UepTipo", "UepTipo")
					.WithMany("Ueps")
					.HasForeignKey("UepTipoId")
					.OnDelete(DeleteBehavior.Restrict);
			});
#pragma warning restore 612, 618
		}
	}
}
