//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneProject.Core.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensNegocio {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensNegocio() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Automacao.Core.Messages.MensagensNegocio", typeof(MensagensNegocio).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Incluído com Sucesso!.
        /// </summary>
        public static string MSG01 {
            get {
                return ResourceManager.GetString("MSG01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Alterado com Sucesso!.
        /// </summary>
        public static string MSG02 {
            get {
                return ResourceManager.GetString("MSG02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro Excluído com Sucesso!.
        /// </summary>
        public static string MSG03 {
            get {
                return ResourceManager.GetString("MSG03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro não Existe!.
        /// </summary>
        public static string MSG04 {
            get {
                return ResourceManager.GetString("MSG04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro encontrado..
        /// </summary>
        public static string MSG05 {
            get {
                return ResourceManager.GetString("MSG05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro já existe para a Unidade, Data e Hora informados. Registro não foi salvo..
        /// </summary>
        public static string MSG06 {
            get {
                return ResourceManager.GetString("MSG06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao tentar salvar o registro no banco de dados, caso o problema persista, por favor entrar em contato com o suporte..
        /// </summary>
        public static string MSG07 {
            get {
                return ResourceManager.GetString("MSG07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro já existe com mesmo nome, por favor informe outro nome..
        /// </summary>
        public static string MSG08 {
            get {
                return ResourceManager.GetString("MSG08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este registro não pode ser excluído, pois há alguma informação associada a ele..
        /// </summary>
        public static string MSG09 {
            get {
                return ResourceManager.GetString("MSG09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro já associado..
        /// </summary>
        public static string MSG10 {
            get {
                return ResourceManager.GetString("MSG10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros &apos;Não identificado&apos; não podem ser alterados..
        /// </summary>
        public static string MSG11 {
            get {
                return ResourceManager.GetString("MSG11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registros &apos;Não identificado&apos; não podem ser excluídos..
        /// </summary>
        public static string MSG12 {
            get {
                return ResourceManager.GetString("MSG12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associações com &apos;Não identificado&apos; não podem ser desfeitas..
        /// </summary>
        public static string MSG13 {
            get {
                return ResourceManager.GetString("MSG13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro já existe com mesma chave..
        /// </summary>
        public static string MSG14 {
            get {
                return ResourceManager.GetString("MSG14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro já existe para a Unidade e Checksum informados. Registro não foi salvo..
        /// </summary>
        public static string MSG15 {
            get {
                return ResourceManager.GetString("MSG15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dados de configuração não estão cadastrados. Importação não foi salva..
        /// </summary>
        public static string MSG16 {
            get {
                return ResourceManager.GetString("MSG16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro já existe com mesmo Código Sap e Código informados, por favor informe dados diferentes..
        /// </summary>
        public static string MSG17 {
            get {
                return ResourceManager.GetString("MSG17", resourceCulture);
            }
        }
    }
}
